version: "3.9"

services:
  second_app:
    build:
      context: ./secondapp/
      args:
        - NODE_ENV=development
    env_file:
      - ./secondapp/my-app/.env.development
    environment:
      - NODE_ENV=development
      #- EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.183
      #- REACT_NATIVE_PACKAGER_HOSTNAME=192.168.235.237
    ports:
      - '19006:19006'
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      
    volumes:
      - ./secondapp/my-app:/opt/secondapp/my-app
      #- notused:/opt/secondapp/my-app/node_modules
      - /opt/secondapp/my-app/node_modules
    stdin_open: true # docker run -i
    tty: true # docker run -t
    healthcheck:
      disable: true
